### ISSUE TITLE
Security Risk, Script Is not removing old ip list from firewalls?

### ISSUE THREAD

**Issue by MaxBoyman** [arvancloud/ar-ipwhitelist#14]
It seems that this script can cause a security risk by not removing old ip list from firewalls. I tested this on ufw, csf and firewalld. this could be harmful in case of any other changes on this specific ip usages for other purpose by arvancloud or any other service providers.
please fix this as soon as possible.
best regards, max.

**Comment by hatamiarash7** [comment]
Solved. #19

**Comment by MaxBoyman** [comment]
Althought it's being late but thanks.
