### ISSUE TITLE
The number of IPs  

### ISSUE THREAD

**Issue by rezshar** [arvancloud/ar-ipwhitelist#8]
Are all the IPs in the range of IPs specified in your property?
Putting all these IPs in the firewall whitelist will create a security problem if the IPs are not in your possession. Do you guarantee that there will be no problem?
Regards

**Comment by 3a8r** [comment]
Hi.
You need just to ignore this IPs in your rate limit. You can treat this IPs in your security modules just like another ones. Just the number of requests from these IPs are higher than another ones.
